# Application Name
spring.application.name=AgriLinkerBackend

logging.level.org.springframework.ai=DEBUG
logging.level.web=DEBUG

# MongoDB connection
spring.data.mongodb.uri=mongodb+srv://kotikawattamadhusha_db_user:zlEPtAWO2YAKnakV@agrilinkersecurity.peiznwj.mongodb.net/AgriLinkerSecurityDB?retryWrites=true&w=majority&ssl=true
# Server port
server.port=8081

# JWT configuration
jwt.secret=Zx3!5yKp8Qw7#R4mU2tBvC6fN9gH1jL0
jwt.expiration=86400000

# File upload configuration
# Path where uploaded images/files will be stored
file.upload-dir=uploads

# Maximum file size (optional, adjust as needed)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


huggingface.token=${HF_TOKEN:}
huggingface.model=distilbert/distilbert-base-uncased-finetuned-sst-2-english

# Groq API Configuration
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile




